### ISSUE TITLE
project presentation slides

### ISSUE THREAD

**Issue by Wishula** [cepdnaclk/e19-CO227-A-Simple-Web-or-Mobile-Application-For-A-Gym#3]
- [x] problem domain and the specific problem to solve
- [x] Viability of the proposed solution
- [x] diagrams/figures to describe the solution
- [x] The reasoning behind design choices made
- [x] Viability of the plan of work
- [x] the presentation

**Comment by hirushig** [comment]
https://www.canva.com/design/DAFsMdOf_jg/zpOysev_AV0hm4n4bw1ynQ/edit?utm_content=DAFsMdOf_jg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Presentation Slides
